### PR TITLE
clean code

### PR DESCRIPTION
**Pull request by AngryShoes**
## Don't worry! No significant update.

just include:
- clean code
- slight refact code

*be happy*
😃

### CODE REVIEW

**Comment by WangRui321** [comment]
Firstly,Thanks.
But there are some conflicts in your requests, please try to resolve it.

**Comment by AngryShoes** [comment]
ok. I will look into it.
thank you.

---Original---

**Comment by AngryShoes** [comment]
Conflicts has been  resolved.

**Comment by AngryShoes** [comment]
Hi buddy, does this **services.AddAutofac()** was registered in corecontainer? or framework? I meet this complie error.

**Comment by WangRui321** [comment]
That's in the assembly of Autofac.Extensions.DependencyInjection.
image

**Pull request closed without merging**
